import { Button, Card, Input, Pagination, Popconfirm, Select, Space, Switch, Table, Typography, message } from 'antd';
import { useState } from 'react';
import { useMallData } from '../../hooks/useMallData';
import { usePagination } from '../../hooks/usePagination';
import { formatPrice, getPermissionLabel } from '../../utils/formatters';
import { createProduct, createCategory, deleteCategory, deleteProduct, getAdmins, getCategories, getOrders, getProducts, getRoles, toggleProductStatus, updateCategory, updateOrderStatus, updateProduct } from '../../utils/mallStore';

function ProductEditor({ categories, editingProduct, onCancel, onSubmit }) {
  const [form, setForm] = useState(editingProduct || { name: '', categoryId: categories[0]?.id, price: 0, marketPrice: 0, stock: 0, cover: '', specsText: '', description: '', detail: '', published: true });
  return <Card className="section-card"><Typography.Title level={4}>{editingProduct ? '编辑商品' : '新增商品'}</Typography.Title><div className="simple-form-grid"><input className="simple-input" placeholder="商品名称" value={form.name} onChange={function (event) { setForm({ ...form, name: event.target.value }); }} /><select className="simple-input" value={form.categoryId} onChange={function (event) { setForm({ ...form, categoryId: event.target.value }); }}>{categories.map(function (item) { return <option key={item.id} value={item.id}>{item.name}</option>; })}</select><input className="simple-input" placeholder="售价" type="number" value={form.price} onChange={function (event) { setForm({ ...form, price: Number(event.target.value) }); }} /><input className="simple-input" placeholder="划线价" type="number" value={form.marketPrice} onChange={function (event) { setForm({ ...form, marketPrice: Number(event.target.value) }); }} /><input className="simple-input" placeholder="库存" type="number" value={form.stock} onChange={function (event) { setForm({ ...form, stock: Number(event.target.value) }); }} /><input className="simple-input" placeholder="商品图片链接" value={form.cover} onChange={function (event) { setForm({ ...form, cover: event.target.value }); }} /><input className="simple-input" placeholder="规格列表，逗号分隔" value={form.specsText || form.specs?.join(', ') || ''} onChange={function (event) { setForm({ ...form, specsText: event.target.value }); }} /><input className="simple-input" placeholder="商品简介" value={form.description} onChange={function (event) { setForm({ ...form, description: event.target.value }); }} /><input className="simple-input" placeholder="商品详情" value={form.detail} onChange={function (event) { setForm({ ...form, detail: event.target.value }); }} /><label className="simple-checkbox"><input checked={Boolean(form.published)} type="checkbox" onChange={function (event) { setForm({ ...form, published: event.target.checked }); }} />是否上架</label></div><Space><Button onClick={onCancel}>取消</Button><Button type="primary" onClick={function () { if (!form.name || !form.cover || !form.description || !form.detail) { message.warning('请完整填写商品信息'); return; } onSubmit({ ...form, specs: String(form.specsText || '').split(',').map(function (item) { return item.trim(); }).filter(Boolean), tags: editingProduct?.tags || ['后台新增'] }); }}>保存商品</Button></Space></Card>;
}

function CategoryEditor({ editingCategory, onCancel, onSubmit }) {
  const [form, setForm] = useState(editingCategory || { name: '', description: '', cover: '', active: true });
  return <Card className="section-card"><Typography.Title level={4}>{editingCategory ? '编辑分类' : '新增分类'}</Typography.Title><div className="simple-form-grid"><input className="simple-input" placeholder="分类名称" value={form.name} onChange={function (event) { setForm({ ...form, name: event.target.value }); }} /><input className="simple-input" placeholder="分类描述" value={form.description} onChange={function (event) { setForm({ ...form, description: event.target.value }); }} /><input className="simple-input" placeholder="封面链接" value={form.cover} onChange={function (event) { setForm({ ...form, cover: event.target.value }); }} /><label className="simple-checkbox"><input checked={Boolean(form.active)} type="checkbox" onChange={function (event) { setForm({ ...form, active: event.target.checked }); }} />是否启用</label></div><Space><Button onClick={onCancel}>取消</Button><Button type="primary" onClick={function () { if (!form.name || !form.description || !form.cover) { message.warning('请完整填写分类信息'); return; } onSubmit(form); }}>保存分类</Button></Space></Card>;
}

export function ProductManagePage() {
  const { page, pageSize, setPage } = usePagination(6);
  const [keyword, setKeyword] = useState('');
  const [categoryId, setCategoryId] = useState('all');
  const [editingProduct, setEditingProduct] = useState(null);
  const [editorOpen, setEditorOpen] = useState(false);
  const categories = useMallData(function () { return getCategories(); }, []);
  const result = useMallData(function () { return getProducts({ keyword, categoryId, page, pageSize, includeUnpublished: true }); }, [keyword, categoryId, page, pageSize]);
  const columns = [{ title: '商品', dataIndex: 'name', render(name, record) { return <Space><img alt={name} className="table-thumb" src={record.cover} /><div><Typography.Text strong>{name}</Typography.Text><div className="muted-text">{record.categoryName}</div></div></Space>; } }, { title: '价格', render(_, record) { return formatPrice(record.price); } }, { title: '库存', dataIndex: 'stock' }, { title: '销量', dataIndex: 'sales' }, { title: '状态', render(_, record) { return <Switch checked={record.published} checkedChildren="上架" unCheckedChildren="下架" onChange={function () { toggleProductStatus(record.id); }} />; } }, { title: '操作', render(_, record) { return <Space><Button type="link" onClick={function () { setEditingProduct({ ...record, specsText: record.specs.join(', ') }); setEditorOpen(true); }}>编辑</Button><Popconfirm title="确认删除该商品吗？" onConfirm={function () { deleteProduct(record.id); message.success('商品已删除'); }}><Button danger type="link">删除</Button></Popconfirm></Space>; } }];
  return <div className="page-section-stack"><Card className="section-card"><div className="section-header"><Typography.Title level={3}>商品管理</Typography.Title><Button type="primary" onClick={function () { setEditingProduct(null); setEditorOpen(true); }}>新增商品</Button></div><Space wrap className="filter-row"><Input.Search allowClear placeholder="搜索商品名称" style={{ width: 260 }} onSearch={function (value) { setKeyword(value); setPage(1); }} /><Select options={[{ label: '全部分类', value: 'all' }].concat(categories.map(function (item) { return { label: item.name, value: item.id }; }))} style={{ width: 220 }} value={categoryId} onChange={function (value) { setCategoryId(value); setPage(1); }} /></Space><Table columns={columns} dataSource={result.list} pagination={false} rowKey="id" /><div className="pagination-wrap"><Pagination current={page} pageSize={pageSize} total={result.total} onChange={function (nextPage) { setPage(nextPage); }} /></div></Card>{editorOpen ? <ProductEditor categories={categories} editingProduct={editingProduct} onCancel={function () { setEditorOpen(false); setEditingProduct(null); }} onSubmit={function (values) { if (editingProduct) { updateProduct(editingProduct.id, values); message.success('商品更新成功'); } else { createProduct(values); message.success('商品创建成功'); } setEditorOpen(false); setEditingProduct(null); }} /> : null}</div>;
}

export function CategoryManagePage() {
  const { page, pageSize, setPage } = usePagination(6);
  const [editingCategory, setEditingCategory] = useState(null);
  const [editorOpen, setEditorOpen] = useState(false);
  const result = useMallData(function () { const categories = getCategories(); const start = (page - 1) * pageSize; return { list: categories.slice(start, start + pageSize), total: categories.length }; }, [page, pageSize]);
  const columns = [{ title: '分类名称', dataIndex: 'name', render(name, record) { return <Space><img alt={name} className="table-thumb" src={record.cover} /><div><Typography.Text strong>{name}</Typography.Text><div className="muted-text">{record.description}</div></div></Space>; } }, { title: '商品数量', dataIndex: 'productCount' }, { title: '状态', render(_, record) { return <Switch checked={record.active} checkedChildren="启用" unCheckedChildren="停用" onChange={function (checked) { updateCategory(record.id, { ...record, active: checked }); }} />; } }, { title: '操作', render(_, record) { return <Space><Button type="link" onClick={function () { setEditingCategory(record); setEditorOpen(true); }}>编辑</Button><Popconfirm title="确认删除该分类吗？分类下商品将自动归入手机数码。" onConfirm={function () { deleteCategory(record.id); message.success('分类已删除'); }}><Button danger type="link">删除</Button></Popconfirm></Space>; } }];
  return <div className="page-section-stack"><Card className="section-card"><div className="section-header"><Typography.Title level={3}>分类管理</Typography.Title><Button type="primary" onClick={function () { setEditingCategory(null); setEditorOpen(true); }}>新增分类</Button></div><Table columns={columns} dataSource={result.list} pagination={false} rowKey="id" /><div className="pagination-wrap"><Pagination current={page} pageSize={pageSize} total={result.total} onChange={function (nextPage) { setPage(nextPage); }} /></div></Card>{editorOpen ? <CategoryEditor editingCategory={editingCategory} onCancel={function () { setEditorOpen(false); setEditingCategory(null); }} onSubmit={function (values) { if (editingCategory) { updateCategory(editingCategory.id, values); message.success('分类更新成功'); } else { createCategory(values); message.success('分类创建成功'); } setEditorOpen(false); setEditingCategory(null); }} /> : null}</div>;
}

export function OrderManagePage() {
  const { page, pageSize, setPage } = usePagination(6);
  const [keyword, setKeyword] = useState('');
  const result = useMallData(function () { return getOrders({ keyword, page, pageSize }); }, [keyword, page, pageSize]);
  const columns = [{ title: '订单编号', dataIndex: 'orderNo' }, { title: '用户', render(_, record) { return record.address?.receiver || '用户'; } }, { title: '金额', render(_, record) { return formatPrice(record.totalAmount); } }, { title: '状态', dataIndex: 'status' }, { title: '操作', render(_, record) { return <Select value={record.status} style={{ width: 140 }} options={['待付款', '待发货', '待收货', '已完成', '已取消'].map(function (status) { return { label: status, value: status }; })} onChange={function (value) { updateOrderStatus(record.id, value); message.success('订单状态更新成功'); }} />; } }];
  return <div className="page-section-stack"><Card className="section-card"><div className="section-header"><Typography.Title level={3}>订单管理</Typography.Title></div><Input.Search allowClear placeholder="搜索订单编号" style={{ width: 260, marginBottom: 16 }} onSearch={function (value) { setKeyword(value); setPage(1); }} /><Table columns={columns} dataSource={result.list} pagination={false} rowKey="id" /><div className="pagination-wrap"><Pagination current={page} pageSize={pageSize} total={result.total} onChange={function (nextPage) { setPage(nextPage); }} /></div></Card></div>;
}

export function PermissionPage() {
  const roles = useMallData(function () { return getRoles(); }, []);
  const admins = useMallData(function () { return getAdmins(); }, []);
  return <div className="page-section-stack"><Card className="section-card"><Typography.Title level={3}>角色与权限</Typography.Title><Space direction="vertical" style={{ width: '100%' }}>{roles.map(function (role) { return <Card key={role.id} size="small"><Typography.Title level={5}>{role.name}</Typography.Title><Typography.Paragraph type="secondary">{role.description}</Typography.Paragraph><Space wrap>{role.permissions.map(function (permission) { return <span className="permission-pill" key={permission}>{getPermissionLabel(permission)}</span>; })}</Space></Card>; })}</Space></Card><Card className="section-card"><Typography.Title level={3}>管理员账号</Typography.Title><Table pagination={false} rowKey="id" dataSource={admins} columns={[{ title: '姓名', dataIndex: 'name' }, { title: '账号', dataIndex: 'username' }, { title: '角色', dataIndex: 'roleName' }, { title: '权限模块', render(_, record) { return record.permissions.map(function (item) { return getPermissionLabel(item); }).join('、'); } }]} /></Card></div>;
}
